# 应用名称
spring:
  application:
    name: project-app

  datasource:
    url: jdbc:mysql://120.78.240.226:3306/scutbbs?useSSL=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC
    username: root
    password: 3f6a66df177d0146
server:
  port: 9111
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
